/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AzkarRouteImport } from './routes/azkar'
import { Route as IndexRouteImport } from './routes/index'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarRoute = AzkarRouteImport.update({
  id: '/azkar',
  path: '/azkar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/login': typeof LoginRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/login': typeof LoginRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/login': typeof LoginRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azkar'
    | '/login'
    | '/prayer'
    | '/quran'
    | '/settings'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/azkar' | '/login' | '/prayer' | '/quran' | '/settings' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/azkar'
    | '/login'
    | '/prayer'
    | '/quran'
    | '/settings'
    | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzkarRoute: typeof AzkarRoute
  LoginRoute: typeof LoginRoute
  PrayerRoute: typeof PrayerRoute
  QuranRoute: typeof QuranRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar': {
      id: '/azkar'
      path: '/azkar'
      fullPath: '/azkar'
      preLoaderRoute: typeof AzkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzkarRoute: AzkarRoute,
  LoginRoute: LoginRoute,
  PrayerRoute: PrayerRoute,
  QuranRoute: QuranRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
